TARGET = cpufeat_latency_pointer_chasing_lm

NUCLEI_SDK_ROOT ?= ../../../..
DOWNLOAD=ilm
SRCDIRS = . src
INCDIRS = . inc

COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf  
STDCLIB ?= newlib_full
include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
