TARGET = cpufeat_dcache_replace

NUCLEI_SDK_ROOT ?= ../../../..
DOWNLOAD=sram
SRCDIRS = . src

INCDIRS = . inc
LDFLAGS := -lm

COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf  
include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
