TARGET = cpufeat_low_power_wfe
NUCLEI_SDK_ROOT = ../../../..
DOWNLOAD= ilm
SRCDIRS = . src
INCDIRS = . inc
LDFLAGS := -lm
COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf 

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
