TARGET = cpufeat_icache_lock

NUCLEI_SDK_ROOT ?= ../../../..
DOWNLOAD=sram
SRCDIRS = . src

INCDIRS = . inc

COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf  
include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
