TARGET = cpufeat_dcache_invalid

NUCLEI_SDK_ROOT ?= ../../../..
DOWNLOAD=sram


SRCDIRS = . src
INCDIRS = . inc

COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf -O3

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
