TARGET = cpufeat_latency_load_to_add_cache

NUCLEI_SDK_ROOT ?= ../../../..
DOWNLOAD=sram
SRCDIRS = . src
INCDIRS = . inc

COMMON_FLAGS :=  -gdwarf-4 -gstrict-dwarf
STDCLIB ?= newlib_full
include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
